export enum MovimientoTipo {
  INGRESO = 'INGRESO',
  TRANSFERENCIA = 'TRANSFERENCIA',
  VENTA = 'VENTA',
  MERMA = 'MERMA',
  AJUSTE = 'AJUSTE',
  AJUSTE_POR_CAMBIO = 'AJUSTE_POR_CAMBIO',
  ENCONTRADO = 'ENCONTRADO',
}
